name: QSRRAreaShopAddon
main: com.mcsunnyside.qsareashop.QSRRAreaShopAddon
version: 0.0.2-SNAPSHOT
authors: [Ghost_chu]
description: QSRR's AreaShop Addon
depend: [QuickShop,AreaShop]

api-version: 1.16

permissions:
    quickshop.addon.areashop.bypass:
        description: Allows a player create shop out of areashop region
        default: op